### ISSUE TITLE
createDoiContact should return response?

### ISSUE THREAD

**Issue by masiorama** [getbrevo/brevo-php#16]
Hello there, just a simple question: is `createDoiContact`  ContactsApi method supposed to return response as `createContact` does, or is it right as it is?

**Comment by preetishishodia7** [comment]
Hi  @masiorama 
`createDoiContact` method used to create contact only when that person agrees. Once we hit The `createDoiContact` method is utilized to create a contact only when that person agrees. When we invoke the `createDoiContact` method, it sends an email to the contact, and contact creation only proceeds if the contact agrees. Consequently, this route is expected to function in this manner only, returning a status code of 201 upon success without any response.

In contrast, the `createContact` method creates a contact immediately without waiting for confirmation. Therefore, upon successful creation, it returns the contact's ID immediately in the response.

I hope this clarifies your query. If you still have any doubts, please let me know, and I'll address them accordingly.  
Thank you!

**Comment by stkrelax** [comment]
Is the DOI mail still send when the contact already exists in identified contacts ?

time before it seemed so but meanwhile there seems to be a change in behaviour.
