### ISSUE TITLE
[Feature Request] - Additional filters for Brevo\Client\Api\ContactsApi->getContacts() would be nice.

### ISSUE THREAD

**Issue by rickymathewk** [getbrevo/brevo-php#17]
It would be great, if there are some additional filters at Brevo\Client\Api\ContactsApi->getContacts() [endpoint `GET api.brevo.com/v3/contacts` ]. For instance , if it is able to filter with brevo contact `"attributes"` , then it avoids additional processing based on `"attributes"` , once all the contacts are fetched.

**Comment by preetishishodia7** [comment]
Hi @rickymathewk 

Currently, we do not have a feature to filter contacts based on attributes. You can refer to this [document](https://developers.brevo.com/reference/getcontacts-1) for a list of all the supported filters.
We will discuss this with our product team to determine its feasibility, and we will keep you informed of any updates on this matter.

Thank you for your understanding and patience!

**Comment by kampalex** [comment]
Hello @preetishishodia7

Method `getContacts()` in [`Brevo\Client\Api\ContactsApi`](https://github.com/getbrevo/brevo-php/blob/af3ef22b31572368fef3c4fce6aa5670c714b5d4/lib/Api/ContactsApi.php#L3735) doesn't take the `filters` argument, so the request can't be executed by this API client.
+1 for the feature request @rickymathewk filtering on additional attributes. Currently, only `equals` is supported, but the app.brevo.com environment offers more operators.
