### ISSUE TITLE
lib/Model/Pipelines.php: Cannot use "parent" when current class scope has no parent

### ISSUE THREAD

**Issue by akater** [getbrevo/brevo-php#20]
I successfully instantiated a `Brevo\Client\Api\DealsApi` object.  Calling `crmPipelineDetailsAllGet()` on it, as suggessted in an example in `DealsApi.md`, triggers the following error:

```
Cannot use "parent" when current class scope has no parent
in brevo-php/lib/Model/Pipelines.php
on line 190
```

May be related: #8

**Comment by akater** [comment]
If I redefine `listInvalidProperties()` to always return `array();`, `crmPipelineDetailsAllGet()` returns the following

```
Brevo\Client\Model\Pipelines Object
(
    [container:protected] => Array
        (
        )

)
```

even though there is a default pipeline.  I don't understand anything about PHP but this doesn't feel right.

**Comment by preetishishodia7** [comment]
Hi @akater 
We have fixed this issue in our latest SDK version (.I.e. 1.0.3).

Thank you for your patience and understanding!
