### ISSUE TITLE
Undefined method smtpLogMessageIdDelete ; breaking change in a patch version!

### ISSUE THREAD

**Issue by tristanjahier** [getbrevo/brevo-php#22]
Hello,

Today after updating my Composer dependencies, my tests reported that the Brevo API client was failing:
```
Call to undefined method Brevo\Client\Api\TransactionalEmailsApi::smtpLogMessageIdDelete()
```

After inspecting this repository, I understood that it had been renamed to `smtpLogIdentifierDelete` in version `1.0.3`.

API reference in `v1.0.2`: https://github.com/getbrevo/brevo-php/blob/v1.0.2/docs/Api/TransactionalEmailsApi.md#smtpLogMessageIdDelete.
API reference in `v1.0.3`: https://github.com/getbrevo/brevo-php/blob/v1.0.3/docs/Api/TransactionalEmailsApi.md#smtpLogIdentifierDelete.

I understand that this change was made automatically by Swagger, but this is a (very) bad practice to ship breaking changes in a patch-level version.

I created this issue too to help other developers understand and find a fix more quickly.

**Comment by preetishishodia7** [comment]
Hi @tristanjahier 
Thank you for bringing this to our attention. We have updated our release to a major level instead of a patch.

Your cooperation is greatly appreciated. Thank you.
