### ISSUE TITLE
Please update your PHP Code examples - its confusing

### ISSUE THREAD

**Issue by tbba** [getbrevo/brevo-php#6]
Example
https://developers.brevo.com/reference/getcontactinfo-1

$config = **SendinBlue**\Client\Configuration::getDefaultConfiguration()->setApiKey('api-key', 'YOUR API KEY');
$apiInstance = new **SendinBlue**\Client\Api\ContactsApi...

"SendinBlue"?

**Comment by preetishishodia7** [comment]
Hello @tbba 

I've made adjustments to the code example to align with the Brevo SDK support for this endpoint.

Thank you for your attention to this matter!

**Comment by erfan-ilyas** [comment]
Also Example:

https://developers.brevo.com/reference/sendtransacemail

```
try {
    $result = $apiInstance->sendTransacEmail($sendSmtpEmail);
    print_r($result);
} catch (Exception $e) {
    echo 'Exception when calling TransactionalEmailsApi->sendTransacEmail: ', $e->getMessage(), PHP_EOL;
}
```

"sendTransacEmail: ', $e->getMessage(), PHP_EOL;" ?

Please replace commas with a dot to concatenate a string.

**Comment by preetishishodia7** [comment]
Hello @erfan-ilyas 

Thank you for bringing this to my attention. I will replicate the route once and make any necessary modifications.

Thank you for your cooperation!
