### ISSUE TITLE
Parse Error in lib/model/Pipelines.php

### ISSUE THREAD

**Issue by Csardelacal** [getbrevo/brevo-php#8]
When adding the library to our code, static analysis reported a parse error in this `lib/model/Pipelines.php`.

I pasted it into https://3v4l.org/d2FJ0 and it does indeed reference `parent::` in line 191, but it never extends anything. I'm not sure whether the class is a leftover or a WIP. Could someone clarify?

**Comment by akater** [comment]
If I redefine `listInvalidProperties()` to always return `array();`, `crmPipelineDetailsAllGet()` returns the following:

```
Brevo\Client\Model\Pipelines Object
(
    [container:protected] => Array
        (
        )

)
```

even though there is a default pipeline.  I don't understand anything about PHP but this doesn't feel right.

**Comment by preetishishodia7** [comment]
Hi @Csardelacal 
We have fixed this issue in our latest SDK version (.I.e. 1.0.3).

Thank you for your patience and understanding!
