### ISSUE TITLE
CreateUpdateProduct In EcommerceApi Creating products and can view in https://developers.brevo.com/reference/getproducts but not showing in app.brevo

### ISSUE THREAD

**Issue by sujith2014** [getbrevo/brevo-php#9]
![image (2)](https://github.com/getbrevo/brevo-php/assets/28844666/3239c0e0-bd38-4fa5-94b5-dd15229b1fab)

CreateUpdateProduct In EcommerceApi Creating products and can view in https://developers.brevo.com/reference/getproducts but not showing in  https://app.brevo.com/ecommerce/products 

![image](https://github.com/getbrevo/brevo-php/assets/28844666/78993d34-efe4-47ff-9c70-a3a8edc24efc)

**Comment by preetishishodia7** [comment]
Hi @sujith2014 
The responsibility of displaying content on the UI falls outside the scope of the SDK. Creating and viewing products using the SDK marks the completion of its intended functionality.

The display aspect on the UI is managed by a separate team. If there are any concerns or issues regarding how the content is displayed on the UI, I kindly suggest reaching out to the UI team for assistance, as it is not within the SDK's purview.

Thank you for your understanding and cooperation!
